platform :ios, '12.0'

target 'Todoey-Realm-Beauty' do

  use_frameworks!

  # Pods for Todoey-Realm
  
  pod 'RealmSwift', '~>10'
  pod 'SwipeCellKit'
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
